import json, math, sys

# Each quad: 4 (name, "PIPE|SEP|WORDS") tuples. EASY=6 words/cat, MED=6, HARD=7.
EASY = [
[("Fruits","APPLE|PEAR|PLUM|MANGO|PEACH|GRAPE"),("Dog Breeds","POODLE|BEAGLE|BOXER|PUG|COLLIE|HUSKY"),("Colors","RED|BLUE|GREEN|PURPLE|YELLOW|ORANGE"),("Hand Tools","HAMMER|WRENCH|PLIERS|SAW|CHISEL|DRILL")],
[("Vegetables","CARROT|ONION|SPINACH|CELERY|RADISH|TURNIP"),("Ocean Animals","WHALE|DOLPHIN|SHARK|OCTOPUS|SEAL|WALRUS"),("Musical Instruments","PIANO|VIOLIN|FLUTE|DRUM|TRUMPET|CELLO"),("Weather Words","RAIN|SNOW|FOG|HAIL|THUNDER|BREEZE")],
[("Birds","ROBIN|SPARROW|EAGLE|OWL|CROW|FINCH"),("Sports","SOCCER|TENNIS|HOCKEY|GOLF|RUGBY|BOXING"),("Kitchen Items","SPATULA|WHISK|LADLE|COLANDER|TONGS|SKILLET"),("Flowers","ROSE|TULIP|DAISY|LILY|ORCHID|PEONY")],
[("Farm Animals","COW|PIG|GOAT|SHEEP|HORSE|DUCK"),("Planets","MERCURY|VENUS|MARS|JUPITER|SATURN|NEPTUNE"),("Shapes","CIRCLE|SQUARE|TRIANGLE|OVAL|HEXAGON|RHOMBUS"),("Beverages","COFFEE|TEA|JUICE|SODA|COCOA|LEMONADE")],
[("Insects","ANT|BEETLE|MOTH|CRICKET|WASP|APHID"),("European Countries","FRANCE|SPAIN|ITALY|POLAND|GREECE|NORWAY"),("Body Parts","ELBOW|KNEE|ANKLE|WRIST|SHOULDER|SHIN"),("Desserts","CAKE|PIE|BROWNIE|PUDDING|COBBLER|SUNDAE")],
[("Trees","OAK|MAPLE|BIRCH|PINE|CEDAR|WILLOW"),("Vehicles","TRUCK|VAN|MOTORCYCLE|BUS|TRACTOR|SCOOTER"),("Clothing","SHIRT|PANTS|JACKET|SOCKS|SWEATER|VEST"),("Gemstones","RUBY|EMERALD|TOPAZ|OPAL|SAPPHIRE|GARNET")],
[("Freshwater Fish","TROUT|BASS|PERCH|CATFISH|CARP|PIKE"),("Board Games","CHESS|CHECKERS|BACKGAMMON|DOMINOES|MANCALA|REVERSI"),("Herbs","BASIL|THYME|SAGE|PARSLEY|DILL|OREGANO"),("Furniture","SOFA|DRESSER|DESK|BOOKCASE|OTTOMAN|ARMCHAIR")],
[("Reptiles","LIZARD|GECKO|IGUANA|COBRA|TURTLE|VIPER"),("Breakfast Foods","PANCAKE|WAFFLE|OATMEAL|BAGEL|OMELET|CEREAL"),("Dances","TANGO|WALTZ|SALSA|POLKA|JIG|FLAMENCO"),("School Subjects","MATH|HISTORY|SCIENCE|ART|MUSIC|GEOGRAPHY")],
[("Big Cats","LION|TIGER|LEOPARD|CHEETAH|JAGUAR|COUGAR"),("Breads","BAGUETTE|RYE|SOURDOUGH|PITA|BRIOCHE|CIABATTA"),("US States","TEXAS|OHIO|MAINE|UTAH|IDAHO|KANSAS"),("Toys","YOYO|KITE|TOP|MARBLES|BLOCKS|DOLL")],
[("Shellfish","SHRIMP|CRAB|LOBSTER|CLAM|OYSTER|MUSSEL"),("Card Games","POKER|HEARTS|SPADES|RUMMY|SOLITAIRE|CANASTA"),("Hats","BERET|FEDORA|BEANIE|SOMBRERO|TOPHAT|VISOR"),("Grains","RICE|WHEAT|OATS|BARLEY|QUINOA|MILLET")],
[("Zoo Animals","ZEBRA|GIRAFFE|HIPPO|RHINO|PANDA|KOALA"),("Pizza Toppings","PEPPERONI|MUSHROOM|SAUSAGE|OLIVES|ANCHOVY|HAM"),("Winter Sports","SKIING|SLEDDING|CURLING|LUGE|BOBSLED|SKATING"),("Art Supplies","CRAYON|MARKER|PAINT|EASEL|BRUSH|CANVAS")],
[("Berries","STRAWBERRY|BLUEBERRY|RASPBERRY|CRANBERRY|MULBERRY|GOOSEBERRY"),("Jobs","DOCTOR|TEACHER|PLUMBER|CHEF|PILOT|FARMER"),("Boats","CANOE|KAYAK|YACHT|FERRY|TUGBOAT|SAILBOAT"),("Candy","LOLLIPOP|TAFFY|FUDGE|GUMDROP|CARAMEL|TOFFEE")],
[("Nuts","ALMOND|CASHEW|PECAN|WALNUT|PISTACHIO|HAZELNUT"),("African Animals","ELEPHANT|GAZELLE|MEERKAT|WARTHOG|HYENA|BABOON"),("Garden Tools","RAKE|HOE|TROWEL|SHEARS|SPADE|PRUNER"),("Ice Cream Flavors","VANILLA|CHOCOLATE|MINT|MOCHA|SPUMONI|NEAPOLITAN")],
[("Pond Life","FROG|TADPOLE|NEWT|SALAMANDER|TOAD|MINNOW"),("Fast Food Items","BURGER|FRIES|NUGGETS|TACO|HOTDOG|SHAKE"),("Months","JANUARY|MARCH|APRIL|JUNE|AUGUST|OCTOBER"),("Dairy Products","MILK|CHEESE|YOGURT|BUTTER|CREAM|KEFIR")],
[("Dinosaurs","T-REX|RAPTOR|STEGOSAURUS|TRICERATOPS|BRONTOSAURUS|PTERODACTYL"),("Citrus Fruits","LEMON|LIME|GRAPEFRUIT|TANGERINE|POMELO|KUMQUAT"),("Camping Gear","TENT|LANTERN|SLEEPING BAG|COMPASS|CANTEEN|FIREWOOD"),("Sewing Items","NEEDLE|THREAD|THIMBLE|BOBBIN|PINCUSHION|FABRIC")],
[("Rodents","MOUSE|RAT|SQUIRREL|HAMSTER|GERBIL|CHIPMUNK"),("Condiments","KETCHUP|MUSTARD|MAYO|RELISH|TARTAR|AIOLI"),("Track Events","SPRINT|HURDLES|DISCUS|JAVELIN|RELAY|MARATHON"),("Bathroom Items","TOWEL|SOAP|SHAMPOO|LOOFAH|RAZOR|FLOSS")],
[("Primates","GORILLA|CHIMP|ORANGUTAN|LEMUR|GIBBON|MACAQUE"),("Soups","CHOWDER|BISQUE|MINESTRONE|GUMBO|BROTH|RAMEN"),("Landforms","MOUNTAIN|VALLEY|CANYON|PLATEAU|MESA|DUNE"),("Office Supplies","STAPLER|PAPERCLIP|FOLDER|ENVELOPE|TAPE|BINDER")],
[("Baby Animals","CALF|FOAL|CUB|KITTEN|PUPPY|DUCKLING"),("Pasta Shapes","PENNE|ZITI|FUSILLI|RIGATONI|LINGUINE|ORZO"),("Music Genres","JAZZ|BLUES|ROCK|COUNTRY|REGGAE|FOLK"),("Cleaning Supplies","MOP|BROOM|SPONGE|BUCKET|DUSTER|VACUUM")],
[("Types of Sharks","HAMMERHEAD|MAKO|BULL|GOBLIN|THRESHER|NURSE"),("Root Vegetables","BEET|PARSNIP|GINGER|YAM|CASSAVA|RUTABAGA"),("Sky Objects","STAR|MOON|COMET|METEOR|NEBULA|GALAXY"),("Footwear","SNEAKER|SANDAL|LOAFER|CLOG|MOCCASIN|SLIPPER")],
[("Mythical Creatures","DRAGON|UNICORN|GRIFFIN|PHOENIX|MERMAID|TROLL"),("Sandwiches","BLT|CLUB|REUBEN|PANINI|SUB|GRINDER"),("Exercises","PUSHUP|SITUP|SQUAT|LUNGE|PLANK|CRUNCH"),("Spices","CINNAMON|NUTMEG|PAPRIKA|CUMIN|CLOVE|TURMERIC")],
[("Pets","PARAKEET|GOLDFISH|FERRET|RABBIT|CANARY|GUPPY"),("Mexican Foods","BURRITO|QUESADILLA|ENCHILADA|TAMALE|NACHOS|FAJITA"),("Recess Games","DODGEBALL|KICKBALL|TAG|HOPSCOTCH|FOURSQUARE|LEAPFROG"),("Metals","GOLD|SILVER|COPPER|IRON|TIN|ZINC")],
[("Rivers","NILE|AMAZON|DANUBE|THAMES|VOLGA|GANGES"),("Cheeses","CHEDDAR|BRIE|GOUDA|FETA|SWISS|PARMESAN"),("Halloween Words","GHOST|WITCH|PUMPKIN|SKELETON|COBWEB|CAULDRON"),("String Instruments","GUITAR|BANJO|HARP|UKULELE|MANDOLIN|FIDDLE")],
[("Deserts","SAHARA|GOBI|MOJAVE|KALAHARI|ATACAMA|NEGEV"),("Cookies","SNICKERDOODLE|MACAROON|GINGERSNAP|SHORTBREAD|BISCOTTI|WAFER"),("Circus Words","CLOWN|TRAPEZE|JUGGLER|RINGMASTER|ACROBAT|TIGHTROPE"),("Bones","FEMUR|SKULL|RIB|TIBIA|SPINE|PELVIS")],
[("Mountains","EVEREST|DENALI|FUJI|RAINIER|MATTERHORN|ARARAT"),("Sushi Words","WASABI|NORI|SASHIMI|TEMPURA|MISO|EDAMAME"),("Playground Equipment","SWING|SLIDE|SEESAW|SANDBOX|MONKEY BARS|MERRY-GO-ROUND"),("Shades of Blue","NAVY|TEAL|COBALT|AZURE|INDIGO|CERULEAN")],
[("Farm Crops","CORN|SOYBEAN|ALFALFA|COTTON|SORGHUM|FLAX"),("Pies","CHERRY|RHUBARB|CUSTARD|MERINGUE|KEYLIME|SWEET POTATO"),("Sea Birds","GULL|PELICAN|ALBATROSS|PUFFIN|TERN|CORMORANT"),("Hairstyles","PONYTAIL|BRAID|BUN|MOHAWK|PIXIE|MULLET")],
[("Constellations","ORION|CASSIOPEIA|GEMINI|TAURUS|LYRA|DRACO"),("Salad Greens","LETTUCE|KALE|ARUGULA|ROMAINE|ENDIVE|WATERCRESS"),("Percussion Instruments","TAMBOURINE|XYLOPHONE|CYMBALS|BONGOS|MARACAS|GONG"),("Writing Tools","PEN|PENCIL|CHALK|QUILL|STYLUS|TYPEWRITER")],
[("Beach Items","SEASHELL|SUNSCREEN|UMBRELLA|PAIL|SURFBOARD|SNORKEL"),("Types of Cake","CHEESECAKE|CUPCAKE|FRUITCAKE|SHORTCAKE|POUNDCAKE|BUNDT"),("Wild West Words","SHERIFF|SALOON|LASSO|OUTLAW|WAGON|SPURS"),("Languages","SPANISH|FRENCH|GERMAN|JAPANESE|ARABIC|HINDI")],
[("Chess Pieces","KING|QUEEN|ROOK|BISHOP|KNIGHT|PAWN"),("Tropical Fruits","PAPAYA|GUAVA|PINEAPPLE|COCONUT|LYCHEE|PASSIONFRUIT"),("Space Travel Words","ROCKET|ASTRONAUT|ORBIT|LAUNCHPAD|SATELLITE|CAPSULE"),("Fabrics","DENIM|SILK|WOOL|LINEN|VELVET|CORDUROY")],
[("Currencies","DOLLAR|EURO|PESO|YEN|RUPEE|FRANC"),("Melons","WATERMELON|CANTALOUPE|HONEYDEW|CASABA|CRENSHAW|MUSKMELON"),("Fairy Tale Characters","GIANT|ELF|WIZARD|PRINCESS|OGRE|GNOME"),("Winter Clothing","SCARF|MITTENS|PARKA|EARMUFFS|BOOTS|GLOVES")],
[("Sundae Toppings","SPRINKLES|SYRUP|MARSHMALLOWS|GUMMIES|PEANUTS|WHIPPED CREAM"),("Marsupials","KANGAROO|WALLABY|WOMBAT|OPOSSUM|QUOKKA|BANDICOOT"),("Amusement Park Words","COASTER|CAROUSEL|ARCADE|BUMPER CARS|FERRIS WHEEL|FUNHOUSE"),("Arctic Animals","NARWHAL|CARIBOU|LEMMING|SNOWY OWL|ARCTIC FOX|MUSKOX")],
]

MED = [
[("Things That Are Red","STOP SIGN|LADYBUG|BRICK|CARDINAL|LOBSTER|TOMATO"),("___ BALL","BASKET|BASE|FOOT|EYE|MEAT|PIN"),("Types of Keys","SKELETON|ALLEN|MASTER|SPARE|MAJOR|MINOR"),("Things in a Wallet","CASH|RECEIPT|LICENSE|COUPON|TICKET|STAMPS")],
[("Rhymes With CAT","HAT|BAT|MAT|GNAT|SLAT|BRAT"),("Nocturnal Animals","RACCOON|POSSUM|BADGER|FIREFLY|COYOTE|AARDVARK"),("Things That Fly","KITE|DRONE|FRISBEE|BLIMP|GLIDER|ARROW"),("Palindromes","LEVEL|RADAR|CIVIC|ROTOR|MADAM|NOON")],
[("SUN Compounds","SUNFLOWER|SUNRISE|SUNBURN|SUNDIAL|SUNSET|SUNROOF"),("Shades of Green","OLIVE|LIME|JADE|MINT|SAGE|KELLY"),("Things With Wheels","WHEELBARROW|UNICYCLE|STROLLER|SKATEBOARD|RICKSHAW|TRICYCLE"),("Words Ending in -ICE","NOTICE|OFFICE|JUSTICE|ADVICE|DEVICE|SERVICE")],
[("Things That Are Cold","IGLOO|GLACIER|POPSICLE|FROST|SLUSH|ICEBERG"),("Hot Things","LAVA|SAUNA|EMBER|FURNACE|GEYSER|BONFIRE"),("Words Before HOUSE","DOG|BIRD|GREEN|LIGHT|WARE|CLUB"),("Onomatopoeia","BUZZ|HISS|CLANG|THUD|SIZZLE|POP")],
[("State Capitals","BOISE|AUSTIN|DENVER|ATLANTA|HELENA|TOPEKA"),("Things in a Gym","TREADMILL|DUMBBELL|BARBELL|KETTLEBELL|ROWER|BENCH"),("Words After SNOW","FLAKE|STORM|PLOW|MOBILE|SHOE|CONE"),("Yellow Things","BANANA|TAXI|CANARY|DANDELION|SCHOOL BUS|MUSTARD")],
[("Types of Puzzles","CROSSWORD|SUDOKU|JIGSAW|RIDDLE|MAZE|REBUS"),("Things That Bounce","TRAMPOLINE|POGO STICK|SPRING|ECHO|CHECK|BASKETBALL"),("Sour Things","LEMON|VINEGAR|PICKLE|TAMARIND|SAUERKRAUT|CRABAPPLE"),("Musical Terms","TEMPO|FORTE|ALLEGRO|PITCH|CHORD|SCALE")],
[("Words Before STICK","YARD|DRUM|CHOP|LIP|MATCH|BROOM"),("Things in a Castle","MOAT|TURRET|DRAWBRIDGE|DUNGEON|THRONE|RAMPART"),("Coffee Drinks","ESPRESSO|LATTE|CAPPUCCINO|AMERICANO|MACCHIATO|CORTADO"),("Slow Animals","SNAIL|SLOTH|TORTOISE|SLUG|MANATEE|STARFISH")],
[("Words After FIRE","WORKS|PLACE|FLY|CRACKER|FIGHTER|DRILL"),("Things That Are Round","GLOBE|COIN|PLATE|HULA HOOP|MEDAL|BUTTON"),("Ways to Say Hello","HOWDY|ALOHA|HIYA|GREETINGS|SALUTATIONS|YO"),("Kitchen Appliances","TOASTER|BLENDER|MICROWAVE|KETTLE|MIXER|GRIDDLE")],
[("Words Before WORM","BOOK|EARTH|SILK|GLOW|TAPE|INCH"),("Purple Things","EGGPLANT|LAVENDER|AMETHYST|LILAC|VIOLET|MULBERRY"),("Loud Sounds","SIREN|FOGHORN|ALARM|EXPLOSION|JACKHAMMER|THUNDERCLAP"),("Things You Roll","DICE|DOUGH|CARPET|BARREL|SLEEVES|EYES")],
[("Words After RAIN","BOW|COAT|DROP|FOREST|CHECK|STORM"),("Desert Things","CACTUS|CAMEL|OASIS|MIRAGE|SCORPION|TUMBLEWEED"),("Birthday Party Items","BALLOONS|CONFETTI|CANDLES|PINATA|STREAMERS|PRESENTS"),("Words Ending in -OO","BAMBOO|TATTOO|CUCKOO|KAZOO|IGLOO|SHAMPOO")],
[("World Landmarks","PYRAMIDS|COLOSSEUM|STONEHENGE|ACROPOLIS|TAJ MAHAL|BIG BEN"),("Things That Melt","BUTTER|WAX|SNOWMAN|CHOCOLATE|CRAYON|GELATO"),("Types of Tea","CHAMOMILE|OOLONG|MATCHA|EARL GREY|ROOIBOS|HIBISCUS"),("Things With Stripes","ZEBRA|BARCODE|REFEREE|CANDY CANE|SKUNK|BUMBLEBEE")],
[("Words After BLACK","SMITH|BERRY|BIRD|OUT|TOP|JACK"),("Things in a Library","SHELF|ATLAS|LIBRARIAN|BOOKMARK|ENCYCLOPEDIA|PERIODICAL"),("Types of Snakes","PYTHON|MAMBA|BOA|RATTLER|GARTER|ADDER"),("Sticky Things","GLUE|HONEY|TAR|GUM|SAP|CARAMEL")],
[("Words Before LIGHT","MOON|DAY|FLASH|SPOT|LIME|CANDLE"),("Bodies of Water","LAGOON|FJORD|STRAIT|BAYOU|INLET|ESTUARY"),("Things That Are Fast","CHEETAH|BULLET|JET|LIGHTNING|EXPRESS|FALCON"),("Cooking Methods","SAUTE|BRAISE|ROAST|POACH|GRILL|STEAM")],
[("Things You Can Break","PROMISE|RECORD|SILENCE|HABIT|NEWS|ICE"),("Things in a Hospital","STETHOSCOPE|GURNEY|SCRUBS|BANDAGE|SYRINGE|CRUTCHES"),("Words Before FISH","JELLY|SWORD|CAT|STAR|GOLD|CUTTLE"),("Slippery Things","EEL|SOAP|GREASE|SLIME|OIL|WATERSLIDE")],
[("Words After OVER","TIME|COAT|LOAD|SIGHT|DUE|HAUL"),("Baking Ingredients","FLOUR|YEAST|BAKING SODA|MOLASSES|CORNSTARCH|SHORTENING"),("Rhymes With BEE","SEA|KEY|SKI|FLEA|TREE|PLEA"),("Ways to Cook Eggs","SCRAMBLED|POACHED|DEVILED|HARDBOILED|OVER EASY|SUNNY SIDE UP")],
]

HARD = [
[("Words Before BOARD","KEY|SURF|SKATE|DASH|CHALK|CLIP|BILL"),("Words Before GAME","CARD|BALL|VIDEO|BOARD|MIND|END|WAR"),("Things With Screens","PHONE|LAPTOP|TABLET|TELEVISION|MONITOR|PROJECTOR|KIOSK"),("Words Before PHONE","MEGA|MICRO|EAR|SAXO|HEAD|SMART|TELE")],
[("Animal Homophones","BARE|HAIR|DEAR|MOUSSE|WAIL|LINKS|HOARSE"),("Salon Words","TRIM|PERM|DYE|BANGS|LATHER|CURLER|BARBER"),("Sound Like Letters","BEE|SEA|JAY|KAY|EX|WHY|CUE"),("Backyard Birds","WREN|CHICKADEE|NUTHATCH|STARLING|GROSBEAK|WAXWING|JUNCO")],
[("Words Before CAKE","CUP|PAN|CHEESE|CARROT|CRAB|SHORT|HOT"),("Root Crops","BEET|PARSNIP|YAM|RUTABAGA|TURNIP|RADISH|GINGER"),("Crustaceans","LOBSTER|SHRIMP|CRAYFISH|BARNACLE|KRILL|PRAWN|CRAWDAD"),("Sweet Things","HONEY|NECTAR|FROSTING|MOLASSES|PRALINE|MARZIPAN|NOUGAT")],
[("___ FLY","DRAGON|BUTTER|FIRE|HORSE|MAY|GAD|SHOO"),("Mythical Beasts","KRAKEN|YETI|SPHINX|HYDRA|CENTAUR|BASILISK|MINOTAUR"),("Spreads for Toast","JAM|JELLY|MARMALADE|HUMMUS|TAHINI|PESTO|GHEE"),("Horse Gear","SADDLE|BRIDLE|STIRRUP|REINS|HALTER|BIT|HARNESS")],
[("Words Before JACK","LUMBER|FLAP|CRACKER|APPLE|CAR|BLACK|BOOT"),("Apple Varieties","FUJI|GALA|HONEYCRISP|MCINTOSH|BRAEBURN|CORTLAND|EMPIRE"),("Pancake Toppings","SYRUP|WHIPPED CREAM|BLUEBERRIES|BANANAS|POWDERED SUGAR|COMPOTE|PECANS"),("Parts of a Car","ENGINE|BUMPER|AXLE|MUFFLER|FENDER|HUBCAP|SPOILER")],
[("Words Before MAN","SNOW|SUPER|HANDY|DOOR|MAIL|BOGEY|FRESH"),("Winter Weather","BLIZZARD|SLEET|FLURRY|WHITEOUT|ICICLE|FROSTBITE|COLDSNAP"),("Parts of a Door","KNOB|HINGE|JAMB|DEADBOLT|PEEPHOLE|KNOCKER|THRESHOLD"),("Things in a Mailbox","LETTER|POSTCARD|PARCEL|FLYER|CATALOG|MAGAZINE|BILL")],
[("Words Before STONE","LIME|COBBLE|MILE|KEY|GEM|TOMB|CORNER"),("Citrus Varieties","LEMON|ORANGE|GRAPEFRUIT|TANGERINE|POMELO|KUMQUAT|CLEMENTINE"),("Units of Distance","INCH|FOOT|YARD|METER|LEAGUE|FURLONG|FATHOM"),("Jewelry Gems","DIAMOND|PEARL|AQUAMARINE|ONYX|TURQUOISE|PERIDOT|CITRINE")],
[("Things With Teeth","COMB|SAW|ZIPPER|GEAR|COG|SPROCKET|BEAVER"),("Burrowing Rodents","RAT|PORCUPINE|CAPYBARA|VOLE|MARMOT|GOPHER|SQUIRREL"),("Computer Parts","MOUSE|KEYBOARD|PROCESSOR|MOTHERBOARD|ROUTER|WEBCAM|MODEM"),("Fasteners","BUTTON|SNAP|BUCKLE|CLASP|RIVET|GROMMET|TOGGLE")],
[("Words Before POT","JACK|TEA|CROCK|STOCK|FLOWER|HOT|INK"),("Teas of the World","GREEN|BLACK|HERBAL|PEPPERMINT|JASMINE|DARJEELING|CEYLON"),("Stock Market Words","BULL|BEAR|SHARE|DIVIDEND|TICKER|PORTFOLIO|HEDGE"),("Animals With Horns","RAM|BISON|YAK|IBEX|ORYX|ANTELOPE|BUFFALO")],
[("Silent Letter Words","GNOME|KNIFE|WRIST|ISLAND|DOUBT|SALMON|HOUR"),("Fish on a Menu","TILAPIA|HALIBUT|FLOUNDER|SNAPPER|MAHI|COD|SOLE"),("Units of Time","MINUTE|SECOND|FORTNIGHT|DECADE|CENTURY|ERA|EPOCH"),("Pirate Ship Parts","PLANK|ANCHOR|CANNON|RIGGING|MAST|HELM|SPYGLASS")],
[("Words Before HORN","LONG|BIG|FOG|SHOE|BULL|GREEN|AIR"),("Words Meaning Large","HUGE|GIANT|MASSIVE|COLOSSAL|IMMENSE|VAST|JUMBO"),("Green Hues","OLIVE|LIME|JADE|MINT|SAGE|KELLY|HUNTER"),("Casual Shoes","SNEAKER|SANDAL|LOAFER|CLOG|MOCCASIN|SLIPPER|CLEAT")],
[("Words After BOOK","WORM|CASE|MARK|SHELF|END|KEEPER|CLUB"),("Punctuation Marks","COMMA|COLON|HYPHEN|ELLIPSIS|ASTERISK|APOSTROPHE|TILDE"),("Things in a Courtroom","JUDGE|JURY|GAVEL|WITNESS|VERDICT|BAILIFF|DOCKET"),("Golf Terms","BIRDIE|EAGLE|PAR|CADDIE|FAIRWAY|PUTTER|MULLIGAN")],
[("Kinds of Rings","WEDDING|BOXING|ONION|KEY|NAPKIN|TREE|CIRCUS"),("Shade Trees","SPRUCE|ASPEN|SEQUOIA|REDWOOD|ELM|SYCAMORE|MAGNOLIA"),("Under the Big Top","CLOWN|TRAPEZE|JUGGLER|ACROBAT|RINGMASTER|TIGHTROPE|STILTS"),("Wedding Words","BOUQUET|VOWS|AISLE|GROOM|BRIDE|TOAST|HONEYMOON")],
[("Words Before FALL","WATER|RAIN|NIGHT|PIT|FREE|WIND|SHORT"),("Coastal Waters","LAGOON|FJORD|STRAIT|BAYOU|INLET|ESTUARY|GULF"),("Wind Instruments","OBOE|CLARINET|BASSOON|PICCOLO|SAXOPHONE|TUBA|RECORDER"),("Night Sky Sights","STAR|MOON|COMET|METEOR|NEBULA|GALAXY|AURORA")],
[("Words Before WOOD","DRIFT|FIRE|PLY|DOG|ROSE|SANDAL|HOLLY"),("Garden Flowers","TULIP|DAISY|LILY|ORCHID|PEONY|MARIGOLD|ZINNIA"),("Purebred Dogs","POODLE|BEAGLE|PUG|DACHSHUND|TERRIER|SPANIEL|MASTIFF"),("Holiday Season Words","TINSEL|WREATH|MISTLETOE|GARLAND|ORNAMENT|SLEIGH|EGGNOG")],
[("Words After BREAK","FAST|DOWN|THROUGH|POINT|EVEN|NECK|AWAY"),("Parts of a Guitar","FRET|BRIDGE|TUNER|PICKUP|STRING|HEADSTOCK|CAPO"),("Speedy Things","CHEETAH|BULLET|JET|LIGHTNING|EXPRESS|FALCON|ROADRUNNER"),("Classic Card Games","POKER|RUMMY|CANASTA|EUCHRE|PINOCHLE|WHIST|GO FISH")],
[("Words Before PRINT","BLUE|FOOT|FINGER|NEWS|THUMB|PAW|HAND"),("Anatomy Words","ELBOW|KNEE|ANKLE|SHOULDER|SHIN|HIP|TORSO"),("Blue Hues","NAVY|TEAL|COBALT|AZURE|INDIGO|CERULEAN|PERIWINKLE"),("Newspaper Sections","HEADLINE|EDITORIAL|COMICS|CLASSIFIEDS|OPINION|HOROSCOPE|MASTHEAD")],
[("Words Before BERRY","STRAW|BLUE|BLACK|RASP|CRAN|GOOSE|ELDER"),("Pond Birds","DUCK|SWAN|MALLARD|LOON|HERON|EGRET|IBIS"),("Things in a Barn","HAY|TROUGH|PITCHFORK|STALL|LOFT|MANGER|SADDLE"),("Construction Machines","CRANE|BULLDOZER|EXCAVATOR|BACKHOE|FORKLIFT|PAVER|STEAMROLLER")],
[("Words That Precede HOUSE","DOG|BIRD|GREEN|LIGHT|WARE|PENT|FARM"),("Barnyard Animals","COW|PIG|GOAT|SHEEP|HEN|ROOSTER|MULE"),("Things That Glow","FIREFLY|EMBER|NEON|GLOWSTICK|JELLYFISH|PHOSPHORUS|AURORA"),("Birds of Prey","HAWK|OSPREY|KESTREL|HARRIER|KITE|VULTURE|CONDOR")],
[("___ BAR","CHOCOLATE|SAND|CROW|HANDLE|SPACE|CANDY|SALAD"),("Seaside Finds","SEASHELL|SUNSCREEN|PAIL|SURFBOARD|SNORKEL|DRIFTWOOD|BOARDWALK"),("Salad Ingredients","CROUTON|CUCUMBER|AVOCADO|CHICKPEA|VINAIGRETTE|OLIVE|SPROUTS"),("Rocketry Words","ROCKET|ASTRONAUT|ORBIT|SATELLITE|CAPSULE|THRUSTER|COSMONAUT")],
[("Words After EYE","BALL|BROW|LASH|LID|LINER|PATCH|SHADOW"),("Makeup Items","BLUSH|MASCARA|FOUNDATION|CONCEALER|LIPSTICK|BRONZER|PRIMER"),("Words Before BALL","BASKET|BASE|FOOT|MEAT|PIN|GUM|CANNON"),("Sewing Kit","NEEDLE|THREAD|THIMBLE|BOBBIN|PINCUSHION|FABRIC|SCISSORS")],
[("Words Before COAT","RAIN|TURN|TOP|RED|SUGAR|WAIST|PEA"),("Legumes","LENTIL|PEANUT|PINTO|GARBANZO|EDAMAME|LIMA|FAVA"),("Sweeteners","HONEY|STEVIA|AGAVE|MAPLE|MOLASSES|CANE|NECTAR"),("Red Things","STOP SIGN|LADYBUG|BRICK|CARDINAL|LOBSTER|TOMATO|FIRE TRUCK")],
[("Words Before WALK","BOARD|SIDE|MOON|JAY|CAT|SPACE|CROSS"),("Wild Cats","LION|TIGER|LEOPARD|JAGUAR|COUGAR|LYNX|OCELOT"),("Puzzle Varieties","CROSSWORD|SUDOKU|JIGSAW|RIDDLE|MAZE|REBUS|ANAGRAM"),("Dance Moves","SHIMMY|TWIST|DIP|SPIN|FLOSS|DAB|SHUFFLE")],
[("Words Before DOG","HOT|WATCH|BULL|LAP|CORN|SHEEP|UNDER"),("Worn on the Wrist","BRACELET|CUFF|BANGLE|SWEATBAND|WRISTBAND|CORSAGE|SCRUNCHIE"),("Corn Dishes","GRITS|POLENTA|TORTILLA|SUCCOTASH|HOMINY|TAMALE|CHOWDER"),("Spicy Things","JALAPENO|WASABI|HABANERO|CAYENNE|HORSERADISH|CHIPOTLE|SERRANO")],
[("Words Before SHIP","FRIEND|FLAG|BATTLE|CHAMPION|INTERN|OWNER|RELATION"),("Words Before POLE","NORTH|SOUTH|MAY|TAD|SKI|TOTEM|BEAN"),("Types of Beans","KIDNEY|NAVY|STRING|BLACK|WAX|JELLY|REFRIED"),("Boxing Terms","JAB|HOOK|UPPERCUT|SPARRING|KNOCKOUT|CORNER|BOUT")],
[("Words Before ROOM","BED|BATH|CLASS|MUSH|ELBOW|LEG|SHOW"),("Pizzeria Toppings","PEPPERONI|SAUSAGE|OLIVES|ANCHOVY|HAM|PINEAPPLE|PEPPERS"),("Body Joints","KNEE|ANKLE|HIP|KNUCKLE|JAW|SOCKET|HINGE"),("Living Room Furniture","SOFA|DRESSER|DESK|BOOKCASE|OTTOMAN|ARMCHAIR|FUTON")],
[("Words After HEAD","LINE|ACHE|BAND|QUARTER|PHONE|LIGHT|REST"),("World Currencies","DOLLAR|EURO|PESO|YEN|RUPEE|FRANC|KRONA"),("Musical Ensembles","QUARTET|TRIO|CHOIR|ORCHESTRA|DUET|QUINTET|SYMPHONY"),("Sleep Words","NAP|SLUMBER|SNOOZE|DOZE|SIESTA|HIBERNATE|DREAM")],
[("Words Before TRAP","MOUSE|BEAR|SAND|FLY|SPEED|RAT|BOOBY"),("Types of Bears","GRIZZLY|POLAR|PANDA|KODIAK|SLOTH|SPECTACLED|BROWN"),("Golf Course Features","GREEN|ROUGH|BUNKER|TEE|PIN|FLAGSTICK|DOGLEG"),("Racing Words","LAP|PIT|TURBO|NITRO|CHECKERED|POLE|DRAFT")],
[("Words Before BOX","SAND|MAIL|TOOL|LUNCH|JUKE|MATCH|SHADOW"),("Workbench Tools","HAMMER|WRENCH|PLIERS|CHISEL|SCREWDRIVER|MALLET|FILE"),("Deli Sandwiches","BLT|CLUB|REUBEN|PANINI|SUB|GRINDER|HOAGIE"),("Tennis Terms","ACE|SERVE|VOLLEY|DEUCE|RALLY|LOB|BASELINE")],
[("Words Before MILL","WIND|SAW|TREAD|RUMOR|PEPPER|GRIST|WATER"),("Types of Peppers","BELL|POBLANO|SHISHITO|BANANA|GHOST|ANAHEIM|PIMENTO"),("Parts of a Shoe","SOLE|LACE|HEEL|TONGUE|INSOLE|EYELET|AGLET"),("Things That Ring","TELEPHONE|ALARM|CHIME|GONG|BUZZER|TIMER|SIREN")],
]

def words(s): return s.split("|")

def check_quad(quad, need, tag):
    seen = {}
    ok = True
    for name, ws in quad:
        wl = words(ws)
        if len(wl) < need:
            print(f"QUAD ERR {tag}: '{name}' has {len(wl)} words, needs {need}"); ok = False
        for w in wl:
            if not w or w != w.upper():
                print(f"QUAD ERR {tag}: bad word '{w}' in '{name}'"); ok = False
            if w in seen:
                print(f"QUAD ERR {tag}: dup word '{w}' in '{name}' and '{seen[w]}'"); ok = False
            seen[w] = name
    return ok

ok = True
for i, q in enumerate(EASY): ok &= check_quad(q, 6, f"EASY{i+1}")
for i, q in enumerate(MED):  ok &= check_quad(q, 6, f"MED{i+1}")
for i, q in enumerate(HARD): ok &= check_quad(q, 7, f"HARD{i+1}")
assert len(EASY) == 30 and len(MED) == 15 and len(HARD) == 30, (len(EASY), len(MED), len(HARD))

# category-name usage: each quad is used exactly twice -> names must be unique across quads
names = {}
for tag, pool in (("EASY", EASY), ("MED", MED), ("HARD", HARD)):
    for i, q in enumerate(pool):
        for name, _ in q:
            names.setdefault(name, []).append(f"{tag}{i+1}")
for n, locs in names.items():
    if len(locs) > 1:
        print(f"NAME ERR: '{n}' in {locs}"); ok = False
if not ok: sys.exit(1)

# --- difficulty curve --------------------------------------------------------
# Every knob used to scale with card count, so the pressure was identical at
# level 1 and level 150 (~5x the perfect-solve budget, 60% burial, 3 hints +
# 1 joker throughout). These ramp on level id instead, so difficulty also
# climbs *within* a tier and not only at the 31/61/91/121 boundaries.

TOTAL_LEVELS = 150

def curve(lid):
    p = (lid - 1) / (TOTAL_LEVELS - 1)         # 0.0 at level 1 -> 1.0 at level 150
    tableau_frac = round(0.60 + 0.30 * p, 4)   # share of the deck dealt face-down
    budget_ratio = 3.5 - 2.25 * p              # multiple of a perfect solve
    hints = 3 if p < 0.20 else 2 if p < 0.45 else 1 if p < 0.70 else 0
    jokers = 1 if p < 0.50 else 0
    # Padlocked cards enter at level 61 (5 columns) and double at 91 (6):
    # the engine caps locks at columns - 4, so the count must not outrun
    # the column curve.
    locks = 0 if p < 0.4 else 1 if p < 0.6 else 2
    return tableau_frac, budget_ratio, hints, jokers, locks

def level(lid, diff, quad, lo, hi):
    cats = [{"name": n, "words": words(ws)[lo:hi]} for n, ws in quad]
    cards = sum(len(c["words"]) for c in cats)
    tableau_frac, budget_ratio, hints, jokers, locks = curve(lid)
    # A perfect solve is one placement per card plus one draw per stock card;
    # the engine deals ceil(cards * tableau_frac) to the tableau. Gold cards
    # and locks are budget-neutral by construction (see engine.js), so they
    # don't appear in this formula.
    stock = cards - math.ceil(cards * tableau_frac)
    budget = round((cards + stock) * budget_ratio)
    return {"id": lid, "difficulty": diff, "move_budget": budget,
            "tableau_frac": tableau_frac, "hints": hints, "jokers": jokers,
            "golds": True, "locks": locks,
            "categories": cats}

levels = []
for i in range(30):   # diff 1: 4 words, 16 cards
    levels.append(level(i + 1, 1, EASY[i], 0, 4))
for i in range(30):   # diff 2: 5 words, 20 cards (reversed quad order, different slice)
    levels.append(level(i + 31, 2, EASY[29 - i], 1, 6))
for i in range(15):   # diff 3 first pass
    levels.append(level(i + 61, 3, MED[i], 0, 5))
for i in range(15):   # diff 3 second pass, different slice
    levels.append(level(i + 76, 3, MED[14 - i], 1, 6))
for i in range(30):   # diff 4: 6 words, 24 cards
    levels.append(level(i + 91, 4, HARD[i], 0, 6))
for i in range(30):   # diff 5: 7 words, 28 cards
    levels.append(level(i + 121, 5, HARD[29 - i], 0, 7))
assert len(levels) == TOTAL_LEVELS, len(levels)

with open("/Users/jason/GitHub/Solitaire_Associations/data/levels.json", "w") as f:
    json.dump(levels, f, indent=2)
print(f"wrote {len(levels)} levels")
